### ISSUE TITLE
why does pylit-3 exist now when there's py-weblp ??

### ISSUE THREAD

**Issue by goyalyashpal** [slott56/PyLit-3#8]
https://github.com/slott56/py-web-tool/issues/14#issuecomment-1630873881

**Comment by slott56** [comment]
It might be better to open a discussion on the Wiki page instead of an issue.

See https://github.com/slott56/PyLit-3/wiki for a better place to put your thoughts.

**Comment by goyalyashpal** [comment]
https://github.com/slott56/PyLit-3/wiki/PyLit%E2%80%903-vs-Py%E2%80%90WebLP
